### ISSUE TITLE
Error in scglue.models.fit_SCGLUE

### ISSUE THREAD

**Issue by kchiou** [gao-lab/GLUE#17]
Hi, I was running into issues integrating my RNA and ATAC data and reproduced the same error even when using the same data from the tutorial. Here is what I am running:

```
glue = scglue.models.fit_SCGLUE(
    {"rna": rna, "atac": atac}, graph,
    fit_kws={"directory": "glue"}
)
```
returns this error.

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/klchiou/.local/lib/python3.7/site-packages/scglue/models/__init__.py", line 89, in fit_SCGLUE
    pretrain = model(adatas, sorted(graph.nodes), **pretrain_init_kws)
  File "/home/klchiou/.local/lib/python3.7/site-packages/scglue/models/scglue.py", line 1323, in __init__
    u2c=None if all_ct.empty else sc.Classifier(latent_dim, all_ct.size)
  File "/home/klchiou/.local/lib/python3.7/site-packages/scglue/models/base.py", line 273, in __init__
    self._net = self.NET_TYPE(*args, **kwargs)
  File "/home/klchiou/.local/lib/python3.7/site-packages/scglue/models/scglue.py", line 452, in __init__
    super().__init__(g2v, v2g, x2u, u2x, idx, du, prior)
  File "/home/klchiou/.local/lib/python3.7/site-packages/scglue/models/glue.py", line 232, in __init__
    self.device = autodevice()
  File "/home/klchiou/.local/lib/python3.7/site-packages/scglue/models/nn.py", line 178, in autodevice
    best_devices = np.where(free_mems == free_mems.max())[0]
  File "/home/klchiou/.local/lib/python3.7/site-packages/numpy/core/_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```

Help would be appreciated!

**Comment by Jeff1995** [comment]
Thanks for your interest in GLUE! Do you have GPU on your machine?

Could you please post the output of `nvidia-smi` or run the following lines in Python:

```python
import pynvml
pynvml.nvmlDeviceGetCount()
```

**Comment by kchiou** [comment]
Thank you very much for your quick response and for the very exciting tool.

My previous errors were run on a machine without GPU, but there is GPU support on other nodes of my university's HPC.

The output of `nvidia-smi` was simply `No devices were found` when recreating conditions from my earlier post.

The output of `nvidia-smi` shows this on a node with GPU support (we have several other nodes with different GPU specifications). Is GPU required for running scglue?

```
Mon May 16 02:50:25 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:86:00.0 Off |                    0 |
| N/A   31C    P0    55W / 300W |      0MiB / 16384MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by Jeff1995** [comment]
Thanks! I think I know the reason now.

The current `autodevice` function depends on `pynvml.nvmlDeviceGetCount()` throwing an error to determine whether there are available GPUs. In your case, there is GPU software support on all nodes even if there is no GPU hardware installed, so `pynvml.nvmlDeviceGetCount()` would returns 0 without error on non-GPU nodes.

It will be fixed in the next release of `scglue`. For now you may add the following lines in your script as a workaround:

```python
import pynvml
import scglue

scglue.config.CPU_ONLY = pynvml.nvmlDeviceGetCount() == 0
```

Sorry for the inconvenience!

**Comment by kchiou** [comment]
Thank you! I switched to a node with GPU after your previous message and it seems to be working!

Just now, I tested your workaround and was getting this error:

```
>>> scglue.config.CPU_ONLY = pynvml.nvmlDeviceGetCount() == 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/klchiou/.local/lib/python3.7/site-packages/pynvml/nvml.py", line 1645, in nvmlDeviceGetCount
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetCount_v2")
  File "/home/klchiou/.local/lib/python3.7/site-packages/pynvml/nvml.py", line 780, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_UNINITIALIZED)
pynvml.nvml.NVMLError_Uninitialized: Uninitialized
```

I added `pynvml.nvmlInit()` to initialize NVML and it looks to be working now even on nodes with only CPU. Thank you!

**Comment by Jeff1995** [comment]
Great to hear that! Sorry I forgot about the `nvmlInit()`😅

Let me know if there are further issues!

**Comment by Jeff1995** [comment]
The issue should have been fixed in the latest update (v0.2.2). So no need to add the custom statement if you upgrade😀

**Comment by kchiou** [comment]
Thank you! I got some more information about the specific issue. Our HPC scheduler was assigning my job to open nodes that fit my requested specifications and were available, whether or not they had GPU. In my case, the first available nodes happened to have GPUs installed, but because I did not request GPU, the GPUs were not allocated.

Thank you again!

**Comment by gabumon0** [comment]
> The issue should have been fixed in the latest update (v0.2.2). So no need to add the custom statement if you upgrade😀

I use the scglue v0.2.3, and I run the tutorail on my own dataset, the error still exists.
 
<img width="145" alt="image" src="https://user-images.githubusercontent.com/43290184/222874766-1458a749-ab28-4193-a5ff-904af9b9af44.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/43290184/222874781-0847f0ff-5c5a-48e3-ab62-0f3c5f18468c.png">

also, the function name of scglue v0.2.3 is different from that of tutorial.

**Comment by Jeff1995** [comment]
Hi @gabumon0, thanks for the report! Are you seeing identical errors as the original report? It would be helpful if you post the complete traceback so I can have a closer look.

Meanwhile, it seems that you are running in some kind of container. My current guess is that there might be a problem with the container setting.

**Comment by prachsk** [comment]
Hi @Jeff1995, I also got the same error as the OP. I am running version 0.3.2.

**Comment by Jeff1995** [comment]
Hi @prachsk! Thanks for the report. In v0.3.2 we have guarded the [max-mem line](https://github.com/gao-lab/GLUE/blob/663174274586436302bb00f983ed63b4fa0de5db/scglue/models/nn.py#L179) with a [size check](https://github.com/gao-lab/GLUE/blob/663174274586436302bb00f983ed63b4fa0de5db/scglue/models/nn.py#L176), so the error should be different. Could you post a complete traceback so I can take a closer look?
